### ISSUE TITLE
Extrapolation not working for some BCs

### ISSUE THREAD

**Issue by tlycken** [timholy/Grid.jl#31]
There are still some boundary conditions for which `InterpCubic` (from #19) isn't working correctly. See e.g. [this comment](https://github.com/timholy/Grid.jl/issues/29#issuecomment-48679226) on #29.

**Comment by cmundi** [comment]
Joining very late. In most applications of field theories (EM, QM, solid state, etc.) it is essential to be able to place the boundary at node or mid-node. There are even some edge (pun!) cases where quarter-intervals are numerically convenient. Having node and mid-node will cover most cases and help users write more transparently correct code.

**Comment by tlycken** [comment]
@cmundi: Both node and mid-node are supported in Interpolations.jl in terms of the `GridBehavior` type argument - if the boundaries should be on the outermost datapoint, use `OnGrid`, while if you want the boundary a half-interval outside the otuermost datapoint, use `OnCell`.

**Comment by cmundi** [comment]
Perfect!  Thanks for your reply.
