### ISSUE TITLE
extend interpolation to multichannel images?

### ISSUE THREAD

**Issue by twadleigh** [timholy/Grid.jl#54]
It appears that `InterpGrid` is currently limited to supporting interpolations on `Array`s of `FloatingPoint`s. How difficult would it be to extend it to support, e.g., `RGB`s of `FloatingPoint`s?

From a mathematical perspective, at least, I would think it should be natural to extend interpolation to any type that acts like a vector space over a "field" of `FloatingPoint`s.

If it is anything more than trivial to implement, I'll just implement my own for now, since my current need would be satisfied by bilinear interpolation, but this would certainly represent a longer-term nice-to-have.

**Comment by moon6pence** [comment]
Similar issue for me, I need interpolations on `Array`s of `Complex`. 

I'll try to dig up the internals or simply just try Interpolations.jl.
