### ISSUE TITLE
Subarrays as second argument

### ISSUE THREAD

**Issue by matthieugomez** [timholy/Grid.jl#62]
From a matrix A

```
A = rand(10, 10)
```

I can interpolate with respect to the first dimension
```
 CoordInterpGrid(1:10, A[:, 1], BCnearest, InterpLinear)
```

However, I can't interpolate with respect to the second dimension, i.e. do something like
```
 CoordInterpGrid(1:10, A[1, :], BCnearest, InterpLinear)
 CoordInterpGrid(1:10, slice(A, 1, :), BCnearest, InterpLinear)
```

The only solution is to transpose A so that the order of dimensions is inverted. However, adding a support for subarray would probably be faster, no?

**Comment by timholy** [comment]
Even faster would be to use [Interpolations](https://github.com/tlycken/Interpolations.jl) :smile:. Your timing is impeccable; I just pushed the new README, with benchmarks, a few minutes ago.

Interpolations already supports SubArrays  (or should).

**Comment by matthieugomez** [comment]
It's even better - you implemented lookup wrt some dimension. Exactly what I was looking for.

**Comment by matthieugomez** [comment]
:v:
