### ISSUE TITLE
Not working on Julia 0.5

### ISSUE THREAD

**Issue by Thuener** [timholy/Grid.jl#73]
```
using Grid
x = -1.0:0.1:1.0
z = sin(x)

zi = CoordInterpGrid(x, z, BCnil, InterpQuadratic)
```

21-element Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}:
Error showing value of type Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}:
ERROR: MethodError: no method matching coordlookup(::Tuple{FloatRange{Float64}}, ::Tuple{Int64,Int64})
Closest candidates are:
  coordlookup{N}(::Tuple{Vararg{T,N}}, ::Tuple{Vararg{T,N}}) at /home/tas/.julia/v0.5/Grid/src/coord.jl:33
 in getindex(::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}, ::Int64, ::Int64) at /home/tas/.julia/v0.5/Grid/src/coord.jl:48
 in isassigned(::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}, ::Int64, ::Int64, ::Vararg{Int64,N}) at ./abstractarray.jl:186
 in alignment(::IOContext{Base.Terminals.TTYTerminal}, ::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}, ::Array{Int64,1}, ::Array{Int64,1}, ::Int64, ::Int64, ::Int64) at ./show.jl:1277
 in print_matrix(::IOContext{Base.Terminals.TTYTerminal}, ::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64) at ./show.jl:1407
 in print_matrix(::IOContext{Base.Terminals.TTYTerminal}, ::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}, ::String, ::String, ::String) at ./show.jl:1379
 in #showarray#330(::Bool, ::Function, ::IOContext{Base.Terminals.TTYTerminal}, ::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}, ::Bool) at ./show.jl:1618
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}) at ./REPL.jl:132
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}) at ./REPL.jl:135
 in display(::Grid.CoordInterpGrid{Float64,1,Grid.BCnil,Grid.InterpQuadratic,Tuple{FloatRange{Float64}}}) at ./multimedia.jl:143
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##930#931) at ./REPL.jl:188
 in _start() at ./client.jl:360

**Comment by tomasaschan** [comment]
Is there a reason you're using this package, and not its successor [Interpolations.jl](https://github.com/tlycken/Interpolations.jl)? That package is much more actively maintained by both myself and by Tim (the author of Grid.jl).

**Comment by Thuener** [comment]
Actually no, I will use Interpolations.jl.
Thanks.
